# Generated by Django 6.0.5 on 2026-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Что сделать')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('report', models.TextField(blank=True, verbose_name='Отчет ученика/ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('COMPLETED', 'Проведено'), ('CANCELLED', 'Отменено'), ('MISSED', 'Пропущено')], default='PLANNED', max_length=15)),
                ('material_link', models.URLField(blank=True, verbose_name='Ссылка на материалы')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Условие задачи (Markdown/LaTeX)')),
                ('answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('solution', models.TextField(verbose_name='Разбор решения')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название темы')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
            ],
        ),
    ]
