# Generated by Django 6.0.5 on 2026-05-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_alter_lesson_student_alter_lesson_teacher'),
    ]

    operations = [
    ]
