# Generated by Django 6.0.5 on 2026-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_auto_20260510_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-start_time'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('TODO', 'Не начато'), ('REVIEW', 'На проверке'), ('FIXING', 'Требует исправления'), ('DONE', 'Выполнено')], default='TODO', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material_link',
            field=models.FileField(blank=True, upload_to='', verbose_name='Ссылка на материалы'),
        ),
    ]
