# Generated by Django 6.0.5 on 2026-05-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0006_migrate_hw_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='is_completed',
        ),
    ]
