# Generated by Django 6.0.5 on 2026-05-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_remove_homework_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
    ]
