# Generated by Django 6.0.5 on 2026-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0008_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на Zoom/Телемост'),
        ),
    ]
